// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example/example1.proto

#ifndef PROTOBUF_example_2fexample1_2eproto__INCLUDED
#define PROTOBUF_example_2fexample1_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "pkt2.pb.h"
// @@protoc_insertion_point(includes)
namespace example1 {
class TemperaturePkt;
class TemperaturePktDefaultTypeInternal;
extern TemperaturePktDefaultTypeInternal _TemperaturePkt_default_instance_;
}  // namespace example1
namespace pkt2 {
class Address;
class AddressDefaultTypeInternal;
extern AddressDefaultTypeInternal _Address_default_instance_;
class Field;
class FieldDefaultTypeInternal;
extern FieldDefaultTypeInternal _Field_default_instance_;
class Output;
class OutputDefaultTypeInternal;
extern OutputDefaultTypeInternal _Output_default_instance_;
class Packet;
class PacketDefaultTypeInternal;
extern PacketDefaultTypeInternal _Packet_default_instance_;
class Sql;
class SqlDefaultTypeInternal;
extern SqlDefaultTypeInternal _Sql_default_instance_;
class Variable;
class VariableDefaultTypeInternal;
extern VariableDefaultTypeInternal _Variable_default_instance_;
}  // namespace pkt2

namespace example1 {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_example_2fexample1_2eproto();
void protobuf_InitDefaults_example_2fexample1_2eproto();

// ===================================================================

class TemperaturePkt : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:example1.TemperaturePkt) */ {
 public:
  TemperaturePkt();
  virtual ~TemperaturePkt();

  TemperaturePkt(const TemperaturePkt& from);

  inline TemperaturePkt& operator=(const TemperaturePkt& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TemperaturePkt& default_instance();

  static inline const TemperaturePkt* internal_default_instance() {
    return reinterpret_cast<const TemperaturePkt*>(
               &_TemperaturePkt_default_instance_);
  }

  void Swap(TemperaturePkt* other);

  // implements Message ----------------------------------------------

  inline TemperaturePkt* New() const PROTOBUF_FINAL { return New(NULL); }

  TemperaturePkt* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TemperaturePkt& from);
  void MergeFrom(const TemperaturePkt& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TemperaturePkt* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 device = 1 [(.pkt2.variable) = {
  void clear_device();
  static const int kDeviceFieldNumber = 1;
  ::google::protobuf::uint32 device() const;
  void set_device(::google::protobuf::uint32 value);

  // uint32 time = 2 [(.pkt2.variable) = {
  void clear_time();
  static const int kTimeFieldNumber = 2;
  ::google::protobuf::uint32 time() const;
  void set_time(::google::protobuf::uint32 value);

  // double degrees_c = 3 [(.pkt2.variable) = {
  void clear_degrees_c();
  static const int kDegreesCFieldNumber = 3;
  double degrees_c() const;
  void set_degrees_c(double value);

  // @@protoc_insertion_point(class_scope:example1.TemperaturePkt)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 device_;
  ::google::protobuf::uint32 time_;
  double degrees_c_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_example_2fexample1_2eproto_impl();
  friend void  protobuf_AddDesc_example_2fexample1_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_example_2fexample1_2eproto();
  friend void protobuf_ShutdownFile_example_2fexample1_2eproto();

};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TemperaturePkt

// uint32 device = 1 [(.pkt2.variable) = {
inline void TemperaturePkt::clear_device() {
  device_ = 0u;
}
inline ::google::protobuf::uint32 TemperaturePkt::device() const {
  // @@protoc_insertion_point(field_get:example1.TemperaturePkt.device)
  return device_;
}
inline void TemperaturePkt::set_device(::google::protobuf::uint32 value) {
  
  device_ = value;
  // @@protoc_insertion_point(field_set:example1.TemperaturePkt.device)
}

// uint32 time = 2 [(.pkt2.variable) = {
inline void TemperaturePkt::clear_time() {
  time_ = 0u;
}
inline ::google::protobuf::uint32 TemperaturePkt::time() const {
  // @@protoc_insertion_point(field_get:example1.TemperaturePkt.time)
  return time_;
}
inline void TemperaturePkt::set_time(::google::protobuf::uint32 value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:example1.TemperaturePkt.time)
}

// double degrees_c = 3 [(.pkt2.variable) = {
inline void TemperaturePkt::clear_degrees_c() {
  degrees_c_ = 0;
}
inline double TemperaturePkt::degrees_c() const {
  // @@protoc_insertion_point(field_get:example1.TemperaturePkt.degrees_c)
  return degrees_c_;
}
inline void TemperaturePkt::set_degrees_c(double value) {
  
  degrees_c_ = value;
  // @@protoc_insertion_point(field_set:example1.TemperaturePkt.degrees_c)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace example1

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_example_2fexample1_2eproto__INCLUDED
