#!/bin/sh
export ANDROID_SDK_HOME=/home/andrei/Android/Sdk
export ANDROID_NDK_HOME="$ANDROID_SDK_HOME/ndk-bundle"
export HOSTARCH=linux-x86_64

# armeabi  armeabi-v7a  mips  x86
# aarch64-linux-android arm-linux-androideabi mipsel-linux-android x86
export TARGETARCH=aarch64-linux-android
export VERSION=4.9

export TOOLCHAIN_LOCATION=$ANDROID_NDK_HOME/toolchains/$TARGETARCH-$VERSION/prebuilt/$TARGETARCH/
export PATH="$PATH:$TOOLCHAIN_LOCATION/$TARGETARCH/bin"
export CC="arm-linux-androideabi-gcc"
export CXX="arm-linux-androideabi-g++"
export RANLIB="arm-linux-androideabi-ranlib"
export LD="arm-linux-androideabi-ld"
export AR="arm-linux-androideabi-ar"
export CROSS_COMPILE="arm-linux-androideabi"
