#!/bin/sh
#
#	Build database objects from scratch
#	Parameters: [<destination> [<db host name/address>]]
#	Default database server name is localhost.
#
#

POSTGRES_USER_NAME=
POSTGRES_USER_PASSWORD=

DEST=$1
if [ -z "$DEST" ] ; then
    DEST=.
fi
SQL=$DEST/postgresql.sql
HOST=$2
if [ -z "$HOST" ] ; then
    HOST=localhost
fi
if [ -x `which psql` ] ; then
    psql -h $HOST onewayticket onewayticket -w -f $SQL
else
    echo PostgreSQL client is not installed, building database from generated script $SQL skipped.
fi

POSTGRES_VERSION=9.5
POSTGRES_SCHEMA=iridium
POSTGRES_PORT=5432

psql -h localhost iridium imz -w -c "CREATE DATABASE iridium WITH OWNER = imz ENCODING = 'UTF8';"

exit 0