#!/bin/sh
cd /home/andrei/src/pkt2
./configure
make clean
make

strip tcpreceiver tcpemitter tcpemitter-example1 tcptransmitter example1message1 example1message tcpemitter-iridium mqtt-emitter-iridium handlerpq handlerline handler-google-sheets handlerlmdb  messageemitter message2gateway protoc-gen-pkt2  pkt2dumppq protoc-gen-pkt2 pkt2gateway pkt2receiver pkt2gateway pkt2receiver pkt2 pkt2receiver-check mqtt-receiver freceiver pkt2dumpfcm handler-fcm

scp tcpreceiver tcpemitter tcpemitter-example1 tcptransmitter example1message1 example1message tcpemitter-iridium mqtt-emitter-iridium handlerpq handlerline handler-google-sheets handlerlmdb  messageemitter message2gateway protoc-gen-pkt2  pkt2dumppq protoc-gen-pkt2 pkt2gateway pkt2receiver pkt2gateway pkt2receiver pkt2receiver-check mqtt-receiver freceiver pkt2 pkt2dumpfcm handler-fcm andrei@84.237.111.36:/home/andrei/pkt2/bin
# scp tcpreceiver tcpemitter tcpemitter-example1 tcptransmitter example1message1 example1message tcpemitter-iridium mqtt-emitter-iridium handlerpq handlerline handler-google-sheets handlerlmdb  messageemitter message2gateway protoc-gen-pkt2  pkt2dumppq protoc-gen-pkt2 pkt2gateway pkt2receiver pkt2gateway pkt2receiver pkt2receiver-check mqtt-receiver freceiver pkt2 pkt2dumpfcm handler-fcm andrei@nova.ysn.ru:/home/andrei/pkt2/bin
#scp pkt2.js pkt2.js.nova cert/pkt2-sheets.json andrei@nova.ysn.ru:/home/andrei/pkt2/bin
